# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Childrens App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Childrens App
	pod 'Firebase/Core'
    pod 'Firebase/MLVision'
    pod 'Firebase/MLVisionTextModel'
    pod 'Firebase/MLVisionFaceModel'
    pod 'Firebase/MLVisionBarcodeModel'
    pod 'Firebase/MLVision'
    pod 'Firebase/MLVisionLabelModel'


    pod 'SVProgressHUD'
    pod 'SwiftyJSON'
    pod 'Alamofire'

end
