 platform :ios, '9.0'

target 'LA-HACKS-2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LA-HACKS-2019

  target 'LA-HACKS-2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LA-HACKS-2019UITests' do
    inherit! :search_paths
    # Pods for testing
    pod  'Firebase/Core'
    pod 'Firebase/MLVision'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON'
    pod 'Alamofire'
  end

end
